name = "frederique-ai"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[[rules]]
type = "Text"
globs = ["**/*.txt"]
fallthrough = true

[[d1_databases]]
binding = "DB"
database_name = "kunstpakket-products"
database_id = "b70bd81c-4555-4095-afc8-5787afca02f3"

[[r2_buckets]]
binding = "KUNSTPAKKET_PRODUCTS_BUCKET"
bucket_name = "kunstpakket-products"

[[vectorize]]
binding = "KUNSTPAKKET_PRODUCTS_INDEX"
index_name = "kunstpakket_products_index"

[ai]
binding = "AI"

[[services]]
binding = "ANALYTICS"
service = "bluestars-analytics"

[vars]
WIDGET_LIVE = "true"  # Set to "false" to disable widget (only show with ?f=1)
ANALYTICS_API_URL = "https://bluestars-analytics.lotapi.workers.dev/event"
ANALYTICS_API_KEY = "a2af3bc58e3825d9320ad4cd394a8f82ca5cad077bdac0dcbe7b13e78c5a188d"
ANALYTICS_SITE_ID = "kunstpakket-001"